import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { GlobalStyle } from '@/styles/GlobalStyle';
import Providers from './_providers';
import { Footer } from '@/components/footer/Footer';
import ReduxProvider from './ReduxProvider';
import dynamic from 'next/dynamic';
import { ToastContainer } from 'react-toastify';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600'],
});

export const metadata: Metadata = {
  title: 'App-bank',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const HeaderNoSSR = dynamic(() => import('../components/header/Header'), {
    ssr: false,
  });
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <ReduxProvider>
          <Providers>
            <GlobalStyle />
            {children}
            <ToastContainer autoClose={2000} />
            <Footer />
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
